name: Update README with Random Memes

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Update README timestamps
        run: |
          echo "import re\nimport random\nfrom datetime import datetime\n\nwith open('README.md', 'r') as file:\n    content = file.read()\n\ncurrent_time = int(datetime.now().timestamp())\nrandom_timestamps = [current_time + random.randint(1, 1000000) for _ in range(5)]\n\npattern = r'memer\\.dev/random\\?category=[^&]+&ts=\\d+'\nmatches = re.findall(pattern, content)\n\nfor i, match in enumerate(matches):\n    if i < len(random_timestamps):\n        new_ts = random_timestamps[i]\n        new_url = re.sub(r'ts=\\d+', f'ts={new_ts}', match)\n        content = content.replace(match, new_url)\n\nwith open('README.md', 'w') as file:\n    file.write(content)" > update_readme.py
          python update_readme.py
          
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update meme timestamps [skip ci]"
          git push
